# -*- coding: utf-8 -*-
"""AE_week_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qU8m71cJFb_59BEDaZ82X-S7FtriRtXL
"""

import pandas as pd
import numpy as np
import os

def clean_data():
    raw_file = "iot_sensor_raw_data_extended.csv"
    cleaned_file = "cleaned_iot_sensor_data.csv"

    if not os.path.exists(raw_file):
        print(f"Error: {raw_file} not found.")
        return

    print("==================================================")
    print("Starting Data Cleaning Process for IoT Sensor Data")
    print("==================================================")

    # 1. โหลดข้อมูลดิบเข้ามาก่อน
    df_raw = pd.read_csv(raw_file)
    initial_rows = len(df_raw)
    print(f"1. Loaded raw data: {initial_rows} rows.")

    # 2. ดูว่ามี device_id ที่หายไปไหม (ห้ามเป็นค่าว่างเด็ดขาด)
    # เราจะถือว่าค่าว่างคือ NaN, ข้อความเปล่า หรือเขียนว่า 'NULL'
    missing_dev_mask = df_raw['device_id'].isna() | (df_raw['device_id'].astype(str).str.strip().str.upper() == 'NULL') | (df_raw['device_id'].astype(str).str.strip() == '')
    missing_dev_count = missing_dev_mask.sum()
    print(f"2. Found {missing_dev_count} rows with missing device_id (to be removed).")

    # 3. หาข้อมูลซ้ำซ้อน (พวกที่ device_id กับ timestamp ตรงกันเป๊ะ)
    # นับดูว่าในข้อมูลดิบมีข้อมูลซ้ำกันกี่แถว
    raw_duplicates_count = df_raw.duplicated(subset=['device_id', 'timestamp'], keep='first').sum()
    print(f"3. Found {raw_duplicates_count} duplicate rows in raw data (to be removed).")

    # เริ่มกระบวนการทำความสะอาดข้อมูลจริงๆ แล้ว
    df_clean = df_raw[~missing_dev_mask].copy()

    # ทิ้งข้อมูลที่ซ้ำออกไป
    rows_before_dedup = len(df_clean)
    df_clean = df_clean.drop_duplicates(subset=['device_id', 'timestamp'], keep='first')
    dedup_removed = rows_before_dedup - len(df_clean)
    print(f"   - Removed {dedup_removed} duplicate rows after dropping missing device_id.")

    # 4. จับค่าที่แปลกประหลาด (จะเปลี่ยนพวกค่าผิดปกติให้เป็น NULL/NaN ซะ)
    # ดูค่าอุณหภูมิ (temp_c) ว่ามีอะไรแปลกไหม ถ้าไม่อยู่ระหว่าง 0 ถึง 50 ก็แปลกแน่ๆ
    df_clean['temp_c'] = pd.to_numeric(df_clean['temp_c'], errors='coerce')
    temp_outliers_mask = (df_clean['temp_c'] < 0) | (df_clean['temp_c'] > 50)
    temp_outliers_count = temp_outliers_mask.sum()
    df_clean.loc[temp_outliers_mask, 'temp_c'] = np.nan
    print(f"4. Found {temp_outliers_count} temp_c outliers (converted to NULL).")

    # ดูค่าแบตเตอรี่ (battery) ว่ามีอะไรแปลกไหม ถ้าไม่อยู่ระหว่าง 0 ถึง 100 ก็แปลกแน่ๆ
    df_clean['battery'] = pd.to_numeric(df_clean['battery'], errors='coerce')
    battery_outliers_mask = (df_clean['battery'] < 0) | (df_clean['battery'] > 100)
    battery_outliers_count = battery_outliers_mask.sum()
    df_clean.loc[battery_outliers_mask, 'battery'] = np.nan
    print(f"   - Found {battery_outliers_count} battery outliers (converted to NULL).")

    # 5. จัดรูปแบบค่า motion ให้เรียบร้อย แล้วก็จัดการพวกค่าที่เขียนผิด
    # ถ้าเจอ true, truee, yes ให้แปลงเป็น True  ถ้าเจอ false, falsee, 0 ให้แปลงเป็น False
    # ส่วนพวกที่เขียนอะไรมั่วๆ อย่าง unknown หรือ NULL ก็ให้เป็น NaN ซะ
    def parse_motion(val):
        if pd.isna(val):
            return np.nan
        s = str(val).strip().lower()
        if s in ['true', 'truee', 'yes']:
            return True
        elif s in ['false', 'falsee', '0']:
            return False
        else:
            return np.nan

    motion_before_normalization = df_clean['motion'].copy()
    df_clean['motion'] = df_clean['motion'].apply(parse_motion)

    # นับดูว่ามีค่า motion ที่เขียนผิดแล้วโดนแปลงเป็น NaN ไปกี่ตัว (ไม่นับพวกที่เป็น NaN อยู่แล้ว)
    motion_invalid_count = ((motion_before_normalization.notna()) & (df_clean['motion'].isna())).sum()
    print(f"   - Found {motion_invalid_count} invalid motion formats (converted to NULL).")

    # 6. นับจำนวนค่าว่างก่อนจะเติมข้อมูล
    temp_missing_before = df_clean['temp_c'].isna().sum()
    battery_missing_before = df_clean['battery'].isna().sum()
    motion_missing_before = df_clean['motion'].isna().sum()
    print(f"5. Missing values count (before imputation):")
    print(f"   - temp_c: {temp_missing_before}")
    print(f"   - battery: {battery_missing_before}")
    print(f"   - motion: {motion_missing_before}")

    # จดคอลัมน์ไว้ก่อนว่าแถวไหนบ้างที่โดนเติมข้อมูล เพื่อจะได้ติดป้ายสถานะภายหลัง
    # แถวไหนที่มีค่าว่างอยู่แล้ว หรือโดนแปลงค่าแปลกๆ เป็นว่าง จะโดนติดป้ายว่า 'Cleaned'
    # วิธีทำคือเอาข้อมูลก่อนเติมมาเทียบกับข้อมูลหลังเติม
    # เซฟเงื่อนไขแถวที่มีค่าว่างไว้ก่อน
    needs_imputation_mask = df_clean['temp_c'].isna() | df_clean['battery'].isna() | df_clean['motion'].isna()

    # 7. เติมค่าว่างให้เต็ม
    # เรียงข้อมูลตามเวลาของแต่ละเครื่องก่อน แล้วค่อยเติมข้อมูลย้อนหลัง จะได้ไม่ผิดเพี้ยน
    df_clean = df_clean.sort_values(by=['device_id', 'timestamp']).reset_index(drop=True)
    needs_imputation_mask = df_clean['temp_c'].isna() | df_clean['battery'].isna() | df_clean['motion'].isna()

    # วิธีเติมคือ ดึงค่าก่อนหน้ามาใส่ก่อน ถ้ายังเป็นค่าว่างอยู่ ก็ดึงค่าข้างหลังมาใส่ (แยกทำทีละเครื่อง)
    df_clean['temp_c'] = df_clean.groupby('device_id')['temp_c'].ffill().bfill()
    df_clean['battery'] = df_clean.groupby('device_id')['battery'].ffill().bfill()
    df_clean['motion'] = df_clean.groupby('device_id')['motion'].ffill().bfill()

    # 8. เพิ่มคอลัมน์ data_quality_status เพื่อบอกว่าข้อมูลแถวนั้นสะอาดหรือเปล่า
    df_clean['data_quality_status'] = np.where(needs_imputation_mask, 'Cleaned', 'Good')

    final_rows = len(df_clean)
    print("==================================================")
    print("Cleaning Summary Report")
    print("==================================================")
    print(f"Initial Rows: {initial_rows}")
    print(f"Final Cleaned Rows: {final_rows}")
    print(f"Rows Deleted: {initial_rows - final_rows} (Missing device_id: {missing_dev_count}, Duplicates: {dedup_removed})")
    print("\nAnomalies & Quality Issues Solved:")
    print(f"- Missing Device IDs (Dropped): {missing_dev_count}")
    print(f"- Duplicates Removed: {dedup_removed}")
    print(f"- Temperature Outliers (Converted & Imputed): {temp_outliers_count}")
    print(f"- Battery Outliers (Converted & Imputed): {battery_outliers_count}")
    print(f"- Missing/Invalid Motion Values (Normalized & Imputed): {motion_missing_before}")
    print(f"- Missing Temp/Battery (Imputed): Temp: {temp_missing_before - temp_outliers_count}, Battery: {battery_missing_before - battery_outliers_count}")

    print("\nData Quality Status Distribution in Cleaned Data:")
    print(df_clean['data_quality_status'].value_counts())

    # บันทึกไฟล์ใหม่
    df_clean.to_csv(cleaned_file, index=False)
    print(f"\nCleaned data successfully saved to: {cleaned_file}")
    print("==================================================")

if __name__ == "__main__":
    clean_data()